### ISSUE TITLE
论文所说的是三分类，但为什么csv只给出了01二分类？

### ISSUE THREAD

**Issue by KellanZ** [Aoa0/PassFinder#1]

**Comment by peiyangL** [comment]
我也是对这篇论文感兴趣的读者，我想问下论文中哪里提到了三分类？ 
@KellanZ

**Comment by KellanZ** [comment]
好像是机器密钥，人工密钥，以及false 吧，可能作者将前两者合为1了

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年11月17日 12:08 |
| 收件人 | Aoa0/PassFinder ***@***.***> |
| 抄送人 | KellanZ ***@***.***>,
Mention ***@***.***> |
| 主题 | Re: [Aoa0/PassFinder] 论文所说的是三分类，但为什么csv只给出了01二分类？ (Issue #1) |

我也是对这篇论文感兴趣的读者，我想问下论文中哪里提到了三分类？
@KellanZ

**Comment by peiyangL** [comment]
> 好像是机器密钥，人工密钥，以及false 吧，可能作者将前两者合为1了
> […](#)

刚刚读了一下论文的相应部分，还是没找到对应的说法

**Comment by KellanZ** [comment]
是的，个人猜测

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年11月17日 12:22 |
| 收件人 | Aoa0/PassFinder ***@***.***> |
| 抄送人 | KellanZ ***@***.***>,
Mention ***@***.***> |
| 主题 | Re: [Aoa0/PassFinder] 论文所说的是三分类，但为什么csv只给出了01二分类？ (Issue #1) |

好像是机器密钥，人工密钥，以及false 吧，可能作者将前两者合为1了
…

刚刚读了一下论文的相应部分，还是没找到对应的说法

**Comment by peiyangL** [comment]
> 是的，个人猜测
> […](#)

我是说我没找到你所说的“机器密钥，人工密钥，以及false ”的描述，或许你所说的是sec 3.3的内容，但是这里开源的数据集是对应sec 3.4的moudle，应该是只有2类的

**Comment by KellanZ** [comment]
> > 是的，个人猜测
> > […](#)
> 
> 我是说我没找到你所说的“机器密钥，人工密钥，以及false ”的描述，或许你所说的是sec 3.3的内容，但是这里开源的数据集是对应sec 3.4的moudle，应该是只有2类的
我的意思是这部没有
![图片](https://github.com/Aoa0/PassFinder/assets/98209788/3f61ad15-9b15-40e4-b692-c9a4ca868683)

**Comment by Aoa0** [comment]
论文中的Password Model做的是三分类(random、human-chosen、non-password)，Context Model做的是二分类。Password Model的数据集比较大，已上传到[Google Drive](https://drive.google.com/file/d/1eleQeIQccCztKOWFG9LeZ4SbseCKITp7/view?usp=sharing)。
